name: Build-Windows-Platform

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
          cache: "pip"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Executable
        run: python -m nuitka --assume-yes-for-downloads --standalone --onefile --windows-icon-from-ico=icons/Gw2-64.ico --output-dir=. Gw2-64.py
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Gw2-64.exe
          path: Gw2-64.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Gw2-64.bat
          path: Gw2-64.bat

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: *.exe
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: *.bat
          tag: ${{ github.ref }}
          file_glob: true

